### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by kevinb1003** [mariodian/geary#11]
Hello, how I ca check the order status with the callback?

**Comment by mariodian** [comment]
Hi, you could use something like [this](https://github.com/mariodian/Geary#check-order-status-from-gears-webhook).

`$order` is an array with all the returned values.

**Comment by kevinb1003** [comment]
If I use 'Check order status from Gear's webhook' it say Signature mismatch.. I don't understand why

**Comment by mariodian** [comment]
How are you testing it? What are the steps you've tried?

**Comment by kevinb1003** [comment]
I update the keys and I try: http://myweb.com/call a.php and it say this error..

**Comment by kevinb1003** [comment]
Maybe it works only if the order call the callbacks url?

**Comment by mariodian** [comment]
Yes, because you will have to feed it with the data. Something like this:

`http://myweb.com/calla.php?order_id=1&amount=1&amount_in_btc=0.00000001&amount_paid_in_btc=0.00000001&status=2&address=1NZov2nm6gRCGW6r4q1qHtxXurrWNpPr1q&transaction_ids=["tid1"]&keychain_id=1&last_keychain_id=1&after_payment_redirect_to=http://example.com/payments/success&auto_redirect=true&callback_data=some+random+data`

Please have a look at [the documentation](https://admin.gear.mycelium.com/docs/api/receiving_order_status_change_callback).

For easier testing, I have changed `check_order_callback()` function with static data as per the linked documentation above (don't feed it the GET data in the url, the script will do so automatically).

The code looks like this:

```
public function check_order_callback() {
      $header_signature = 'UeXPK9RlYFFLdYpWeGBpSd4OWslJR076VBQU4prJlzMpe3f2KL4eUVfpiZ+Z9/c71tqYZgYWeIN78NE1/Snmyw==';

      $request_path = $_SERVER['REQUEST_URI'];

      if (!count($_GET)) {
        $_GET = array(
          'order_id' => '1',
          'amount' => '1',
          'amount_in_btc' => '0.00000001',
          'amount_paid_in_btc' => '0.00000001',
          'status' => '2',
          'address' => '1NZov2nm6gRCGW6r4q1qHtxXurrWNpPr1q',
          'transaction_ids' => rawurldecode('["tid1"]'),
          'keychain_id' => '1',
          'last_keychain_id' => '1',
          'after_payment_redirect_to' => 'http://example.com/payments/success',
          'auto_redirect' => 'true',
          'callback_data' => 'some+random+data',
        );
      }

      $nonce = NULL;
      $body = NULL;
      $gateway_secret = 'gateway.secret';

      $request_path = '/payments/callback?order_id=1&amount=1&amount_in_btc=0.00000001&amount_paid_in_btc=0.00000001&status=2&address=1NZov2nm6gRCGW6r4q1qHtxXurrWNpPr1q&transaction_ids=["tid1"]&keychain_id=1&last_keychain_id=1&after_payment_redirect_to=http://example.com/payments/success&auto_redirect=true&callback_data=some+random+data';

      $constant_digest = hash('sha512', $nonce . $body, TRUE);
      $payload = $_SERVER['REQUEST_METHOD'] . $request_path . $constant_digest;
      $raw_signature = hash_hmac('sha512', $payload, $gateway_secret, TRUE);
      $signature = base64_encode($raw_signature);

      if ($signature === $header_signature) {
          return array(
              'order_id'              => $_GET['order_id'],
              'amount'                => $_GET['amount'],
              'amount_in_btc'         => $_GET['amount_in_btc'],
              'amount_paid_in_btc'    => $_GET['amount_paid_in_btc'],
              'status'                => $_GET['status'],
              'address'               => $_GET['address'],
              'transaction_ids'       => $_GET['transaction_ids'],
              'callback_data'         => $_GET['callback_data'],
          );
      } else {
          return FALSE;
      }
    })
```

If you change any of the values in `$_GET` or the `$header_signature` it should fail. Otherwise it returns the array with GET data.

Since I don't see any development with Mycelium Gear I don't feel like writing any tests for this lib. If someone does however, it will be very welcome.

**Comment by kevinb1003** [comment]
Not work.. .continues to say that error

screenshot: http://prntscr.com/h9jxyl
